# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: atd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='atd.proto',
  package='tflite',
  syntax='proto3',
  serialized_options=_b('\n$com.example.android.tflitecamerademoB\025ImageClassifierProtocP\001\242\002\003RTG'),
  serialized_pb=_b('\n\tatd.proto\x12\x06tflite\"\x1c\n\x0bGrpcRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\",\n\tGrpcReply\x12\r\n\x05stage\x18\x01 \x01(\t\x12\x10\n\x08stageAcc\x18\x02 \x01(\x05\x32\x42\n\nImageClass\x12\x34\n\x08getStage\x12\x13.tflite.GrpcRequest\x1a\x11.tflite.GrpcReply\"\x00\x42\x45\n$com.example.android.tflitecamerademoB\x15ImageClassifierProtocP\x01\xa2\x02\x03RTGb\x06proto3')
)




_GRPCREQUEST = _descriptor.Descriptor(
  name='GrpcRequest',
  full_name='tflite.GrpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='tflite.GrpcRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=49,
)


_GRPCREPLY = _descriptor.Descriptor(
  name='GrpcReply',
  full_name='tflite.GrpcReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stage', full_name='tflite.GrpcReply.stage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stageAcc', full_name='tflite.GrpcReply.stageAcc', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['GrpcRequest'] = _GRPCREQUEST
DESCRIPTOR.message_types_by_name['GrpcReply'] = _GRPCREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrpcRequest = _reflection.GeneratedProtocolMessageType('GrpcRequest', (_message.Message,), dict(
  DESCRIPTOR = _GRPCREQUEST,
  __module__ = 'atd_pb2'
  # @@protoc_insertion_point(class_scope:tflite.GrpcRequest)
  ))
_sym_db.RegisterMessage(GrpcRequest)

GrpcReply = _reflection.GeneratedProtocolMessageType('GrpcReply', (_message.Message,), dict(
  DESCRIPTOR = _GRPCREPLY,
  __module__ = 'atd_pb2'
  # @@protoc_insertion_point(class_scope:tflite.GrpcReply)
  ))
_sym_db.RegisterMessage(GrpcReply)


DESCRIPTOR._options = None

_IMAGECLASS = _descriptor.ServiceDescriptor(
  name='ImageClass',
  full_name='tflite.ImageClass',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=97,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='getStage',
    full_name='tflite.ImageClass.getStage',
    index=0,
    containing_service=None,
    input_type=_GRPCREQUEST,
    output_type=_GRPCREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGECLASS)

DESCRIPTOR.services_by_name['ImageClass'] = _IMAGECLASS

# @@protoc_insertion_point(module_scope)
