# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import atd_pb2 as atd__pb2


class ImageClassStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getStage = channel.unary_unary(
        '/tflite.ImageClass/getStage',
        request_serializer=atd__pb2.GrpcRequest.SerializeToString,
        response_deserializer=atd__pb2.GrpcReply.FromString,
        )


class ImageClassServicer(object):
  """Interface exported by the server.
  """

  def getStage(self, request, context):
    """A simple RPC.

    Obtains the feature at a given position.

    A feature with an empty name is returned if there's no feature at the given
    position.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageClassServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getStage': grpc.unary_unary_rpc_method_handler(
          servicer.getStage,
          request_deserializer=atd__pb2.GrpcRequest.FromString,
          response_serializer=atd__pb2.GrpcReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tflite.ImageClass', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
